concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "alpine-runner"
  url = "https://lab.ssafy.com"
  id = 1137
  token = "glrt-t3_13UyY_hg3B_ecgr1Mb4V"
  token_obtained_at = 2025-04-03T01:08:27Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
  volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock", "/var/lib/docker:/var/lib/docker"]
privileged = true
    tls_verify = false
    image = "docker:latest"
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    shm_size = 0
    network_mtu = 0
